### ISSUE TITLE
【レスポンシブ対応】index pageの実装

### ISSUE THREAD

**Issue by Oshu2228** [if-tech-support/todo_team_3#41]
## 実装内容の説明
- index pageのレスポンシブ対応

## TASK
- [ ] index pageのレスポンシブ対応

## その他・備考
-

**Comment by oneoneniaoniao** [comment]
複雑なコンフリクトが発生したため一旦こちらのissueをcloseして、新たなissueとしてbranchを作成させて頂きます。
